ListenAddr: 0.0.0.0:8080
AIDispatcherNodeProxyAddr: http:/172.17.0.1:7002
AITaskExecutorNodeProxyAddr: http://127.0.0.1:8000

AIDispatcherNodeProxyAPIPath:
  - /api/v0/ai/project/register
  - /api/v0/ai/project/unregister

AITaskExecutorNodeProxyAPIPath:
  - /v1/chat/completions
  - /v1/chat/generations
  - /v1/images/edits
  - /v1/models

